"""One-off remap of the category tree to Pedro's own structure (2026-10-08).

Old slug -> new slug (None = retired: its transactions go to Unsorted for re-sorting and the
merchants defaulting to it lose their default). Frozen data: the seed may change again later.
Called by alembic revision e9c1a7d3b542; safe to re-run (a missing old node is skipped)."""

SLUG_MAP: dict[str, str | None] = {
    "cash-giving.giving.charity": None,
    "family-education.children-school.activities-clubs": "family.sports.sports-fees",
    "family-education.children-school.kids-clothes-items": "family.shopping.clothing",
    "family-education.children-school.school-childcare": "family.education.school-fees",
    "family-education.education.books-materials": "family.education.books-staples",
    "family-education.education.courses-training": None,
    "food.dining-out.caf-s-takeaway": "food.eat-out.caf-s-snacks",
    "food.dining-out.food-delivery": "food.eat-out.takeaway-delivery",
    "food.dining-out.restaurants": "food.eat-out.restaurants",
    "health.care.doctors-dental": "health.care.medical-appointments",
    "health.health-cover.health-insurance": "insurances.personal.health-insurance",
    "housing.home-running-costs.household-supplies": None,
    "housing.home-upkeep.furniture-appliances": "housing.home-running-costs.furniture-appliances",
    "housing.home-upkeep.garden-diy": "housing.home-running-costs.garden-diy",
    "housing.home-upkeep.repairs-maintenance": "housing.home-running-costs.repairs-maintenance",
    "housing.property-taxes-insurance.condominium-extras": None,
    "housing.property-taxes-insurance.home-insurance": "insurances.home.home-insurance",
    "housing.property-taxes-insurance.imi-property-tax": "taxes-financial-costs.taxes.imi-property-tax",
    "housing.utilities.internet-tv": "housing.utilities.telecom",
    "housing.utilities.mobile-phones": "housing.utilities.telecom",
    "income.gifts-other.other-income": None,
    "income.investments-interest.dividends": "savings-investments.earnings.dividends",
    "income.investments-interest.interest": "savings-investments.earnings.interest",
    "income.psi.other-psi-income": "income.freelance.ballet-classes",
    "loans-debt-in.money-borrowed.mortgage-drawdown": "loans-debt.money-borrowed.mortgage-drawdown",
    "loans-debt-in.money-borrowed.personal-loan-received": "loans-debt.money-borrowed.personal-loan-received",
    "loans-debt-in.repayments-received.from-family": "loans-debt.money-lent-out.from-family",
    "loans-debt-in.repayments-received.from-friends": "loans-debt.money-lent-out.from-friends",
    "loans-debt.loan-insurance.building-insurance-loan": "insurances.home.building-insurance-house-loan",
    "loans-debt.loan-insurance.life-insurance-loan": "insurances.home.life-insurance-house-loan",
    "loans-debt.money-lent-out.loan-to-family": "loans-debt.money-lent-out.to-family",
    "loans-debt.money-lent-out.loan-to-friends": "loans-debt.money-lent-out.to-friends",
    "personal-lifestyle.leisure.culture-events": "family.leisure.culture-events",
    "personal-lifestyle.leisure.gifts": "family.leisure.gifts",
    "personal-lifestyle.leisure.hobbies-sport": "family.sports.sports-gear",
    "personal-lifestyle.personal.clothing-shoes": "family.personal.clothing",
    "personal-lifestyle.personal.general-shopping": "family.personal.general-shopping",
    "personal-lifestyle.personal.personal-care": "family.personal.personal-care",
    "personal-lifestyle.subscriptions.memberships": None,
    "personal-lifestyle.subscriptions.software-apps": "housing.utilities.software-apps",
    "personal-lifestyle.subscriptions.streaming": "housing.utilities.streaming",
    "refunds-reimbursements.refunds.expense-reimbursements": None,
    "refunds-reimbursements.refunds.insurance-claims": None,
    "refunds-reimbursements.refunds.purchase-refunds": None,
    "savings-investments-in.withdrawals.fund-redemptions": "savings-investments.withdrawals.fund-investment-redemptions",
    "savings-investments.contributions.fund-subscriptions": "savings-investments.contributions.fund-investment-subscriptions",
    "taxes-financial-costs.banking.bank-card-fees": "taxes-financial-costs.financial-costs.bank-card-fees",
    "taxes-financial-costs.banking.insurance-life-other": None,
    "transport.car-running.fuel": "transport.car-running-costs.fuel",
    "transport.car-running.maintenance-repairs": "transport.car-running-costs.car-maintenance-repairs",
    "transport.car-running.tolls-parking": "transport.car-running-costs.tolls-parking",
    "transport.car-yearly.car-insurance": "insurances.cars.car-insurance",
    "transport.car-yearly.inspection-ipo": "transport.car-running-costs.car-inspection-ipo",
    "transport.car-yearly.iuc-road-tax": "taxes-financial-costs.taxes.iuc-road-tax",
}
