"""add commitments table

Revision ID: 0690dd36dcb2
Revises: a7764d2e537c
Create Date: 2026-08-21 16:00:43.671037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0690dd36dcb2'
down_revision: Union[str, Sequence[str], None] = 'a7764d2e537c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'TELECOM', 'INSURANCE', 'SUBSCRIPTIONS', 'GROCERIES', 'HEALTH', 'HOME', 'INCOME', 'TRANSFER', 'ATM_WITHDRAWAL', 'RESTAURANTS', 'SHOPPING', 'OTHER_EXPENSE', 'OTHER', name='category'), nullable=False),
    sa.Column('cadence', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'IRREGULAR', name='cadence'), nullable=False),
    sa.Column('planned_amount', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitments')
    # ### end Alembic commands ###
