"""add linked_transaction_id to transactions

Revision ID: 650bb8ad7210
Revises: d63cba4c90e6
Create Date: 2026-08-24 11:30:20.183934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '650bb8ad7210'
down_revision: Union[str, Sequence[str], None] = 'd63cba4c90e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_linked_transaction_id_transactions', 'transactions',
            ['linked_transaction_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_transactions_linked_transaction_id_transactions', type_='foreignkey'
        )
        batch_op.drop_column('linked_transaction_id')

    # ### end Alembic commands ###
