"""add account_id to documents

Revision ID: 6713a2f9a7c7
Revises: 95db95ba76e3
Create Date: 2026-08-21 18:07:46.063627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6713a2f9a7c7'
down_revision: Union[str, Sequence[str], None] = '95db95ba76e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_documents_account_id_accounts_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_account_id_accounts_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
