"""bank connections

Revision ID: 6d1e9c597432
Revises: e5a1c7f3b920
Create Date: 2026-10-04 21:59:46.954613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d1e9c597432'
down_revision: Union[str, Sequence[str], None] = 'e5a1c7f3b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'FAILED', name='bankconnectionstatus'), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_connections_state'), ['state'], unique=True)

    op.create_table('bank_account_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_links_connection_id'), ['connection_id'], unique=False)

    op.create_table('bank_api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['bank_account_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_api_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_api_calls_link_id'), ['link_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_external_id'), ['external_id'], unique=False)
        batch_op.create_unique_constraint('uq_transactions_account_external', ['account_id', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transactions_account_external', type_='unique')
        batch_op.drop_index(batch_op.f('ix_transactions_external_id'))
        batch_op.drop_column('external_id')

    with op.batch_alter_table('bank_api_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_api_calls_link_id'))

    op.drop_table('bank_api_calls')
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_links_connection_id'))

    op.drop_table('bank_account_links')
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_connections_state'))

    op.drop_table('bank_connections')
    # ### end Alembic commands ###
