"""add debts table

Revision ID: 6f861bafbb41
Revises: 0690dd36dcb2
Create Date: 2026-08-21 16:06:22.041784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f861bafbb41'
down_revision: Union[str, Sequence[str], None] = '0690dd36dcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('FORMAL', 'INFORMAL', name='debtkind'), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('OWED_TO_US', 'OWED_BY_US', name='debtdirection'), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('commitment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debts')
    # ### end Alembic commands ###
