"""add utility_readings table

Revision ID: 76db79deac79
Revises: 21636872a4f1
Create Date: 2026-08-18 14:55:15.593894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76db79deac79'
down_revision: Union[str, Sequence[str], None] = '21636872a4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('utility_type', sa.Enum('ELECTRICITY', 'WATER', 'TELECOM', name='utilitytype'), nullable=False),
    sa.Column('period_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consumption_value', sa.Float(), nullable=True),
    sa.Column('consumption_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('energy_cost', sa.Float(), nullable=True),
    sa.Column('power_cost', sa.Float(), nullable=True),
    sa.Column('fees_taxes_cost', sa.Float(), nullable=True),
    sa.Column('vat_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utility_readings_document_id'), 'utility_readings', ['document_id'], unique=False)
    op.create_index(op.f('ix_utility_readings_period_label'), 'utility_readings', ['period_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_readings_period_label'), table_name='utility_readings')
    op.drop_index(op.f('ix_utility_readings_document_id'), table_name='utility_readings')
    op.drop_table('utility_readings')
    # ### end Alembic commands ###
