"""add merchants table

Revision ID: 95db95ba76e3
Revises: 5d642312b7fc
Create Date: 2026-08-21 17:59:42.162610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95db95ba76e3'
down_revision: Union[str, Sequence[str], None] = '5d642312b7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_category', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'TELECOM', 'INSURANCE', 'SUBSCRIPTIONS', 'GROCERIES', 'HEALTH', 'HOME', 'INCOME', 'TRANSFER', 'ATM_WITHDRAWAL', 'RESTAURANTS', 'SHOPPING', 'OTHER_EXPENSE', 'OTHER', name='category'), nullable=False),
    sa.Column('default_nature', sa.Enum('ESSENTIAL', 'DISCRETIONARY', name='nature'), nullable=True),
    sa.Column('normalized_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('recurring_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_normalized_key'), ['normalized_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_normalized_key'))

    op.drop_table('merchants')
    # ### end Alembic commands ###
