"""add merchant_id to transactions

Revision ID: d63cba4c90e6
Revises: 6713a2f9a7c7
Create Date: 2026-08-21 18:15:00.404485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd63cba4c90e6'
down_revision: Union[str, Sequence[str], None] = '6713a2f9a7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('debt_candidate_reviewed', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_merchant_id_merchants', 'merchants', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_merchant_id_merchants', type_='foreignkey')
        batch_op.drop_column('debt_candidate_reviewed')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
