"""add wiki_pages and wiki_changes tables

Revision ID: ebf9c2a43192
Revises: 8f13589a0f87
Create Date: 2026-08-17 15:44:20.966855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebf9c2a43192'
down_revision: Union[str, Sequence[str], None] = '8f13589a0f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facts_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pages_topic'), 'wiki_pages', ['topic'], unique=True)
    op.create_table('wiki_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_page_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['wiki_page_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_changes_wiki_page_id'), 'wiki_changes', ['wiki_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_changes_wiki_page_id'), table_name='wiki_changes')
    op.drop_table('wiki_changes')
    op.drop_index(op.f('ix_wiki_pages_topic'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    # ### end Alembic commands ###
